### ISSUE TITLE
White text on purple is a bit low contrast

### ISSUE THREAD

**Issue by oliverjam** [fac-23/Juliette-Adam-week3#10]
https://github.com/fac-23/Juliette-Adam-week3/blob/6238599905cedb083141616c69e2280e7b7d0580/style.css#L96-L98

The white body text has quite a low contrast ratio on this purple background color (Lighthouse audit says the contrast is only 2.14). To make this more accessible you could either use darker text or a darker background color.

**Comment by julietteorpen** [comment]
/* CSS HEX */
--united-nations-blue: #6290c3ff;
--aero-blue: #c2e7daff;
--honeydew: #f1ffe7ff;
--space-cadet: #1a1b41ff;
--bitter-lime: #baff29ff;
